In [1]:
import numpy as np

In [8]:
#Array attributes
a=np.array([[1,2,3],[4,5,6]])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

2
(2, 3)
6
int64


In [ ]:
#Array creation function
a=np.zeros((3,3))
print(a)
#print(a[0])

a=np.ones((2,4))
print(a)
#print(a[0][1])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
1.0


In [32]:
#Arange
a=np.arange(1,10)
print(a)
#linspace
a=np.linspace(0,10,9)
print(a)
print(a[1])

[1 2 3 4 5 6 7 8 9]
[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]
1.25


In [37]:
#Slicing #2D
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0:2, 1:3])
#Slicing #1D
a=np.array([10,20,30,40,50])
print(a[1:4])

[[2 3]
 [5 6]]
[20 30 40]


In [38]:
#Arithmetic
a=np.array([10,20,30])
print(a+5)
print(a*2)


[15 25 35]
[20 40 60]


In [39]:
#Mathematical
a=np.array([1,4,9,16])
print(np.sqrt(a))

[1. 2. 3. 4.]
